name: crosscall
description: dart and rust call
version: 0.1.2
repository: https://github.com/Zhou-Pixel/crosscall.git

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  grpc: ^4.0.0
  http2: ^2.3.0
  protobuf: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web: